<template>
  <div id="searchmore">
    <div class="title">数据开放平台API接口查询字段列表</div>
    <table border="1" cellpadding="0" cellspacing="0" class="table1">
      <thead>
        <tr>
          <th>分组</th>
          <th>属性名称</th>
          <th>检索语法</th>
          <th>多值(不可排序)</th>
          <th>示例</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td rowspan="9">地域</td>
          <td>数据来源国别</td>
          <td>dac</td>
          <td>否</td>
          <td>dac:US</td>
        </tr>
        <tr>
          <td>专利公开国别</td>
          <td>pnc</td>
          <td>否</td>
          <td>pnc:US</td>
        </tr>
        <tr>
          <td>专利申请国别</td>
          <td>anc</td>
          <td>否</td>
          <td>anc:US</td>
        </tr>
        <tr>
          <td>申请人国别</td>
          <td>ap-country</td>
          <td>否</td>
          <td>ap-country:JP</td>
        </tr>
        <tr>
          <td>申请人省市</td>
          <td>ap-province</td>
          <td>否</td>
          <td>ap-province:四川省</td>
        </tr>
        <tr>
          <td>申请人县</td>
          <td>ap-county</td>
          <td>否</td>
          <td>ap-county:武侯区</td>
        </tr>
        <tr>
          <td>申请人地市</td>
          <td>ap-city</td>
          <td>否</td>
          <td>ap-city:成都市</td>
        </tr>
        <tr>
          <td>发明人国别</td>
          <td>in-country</td>
          <td>是</td>
          <td>in-country:FR</td>
        </tr>
        <tr>
          <td>优先权国别</td>
          <td>pr-au</td>
          <td>否</td>
          <td>pr-au:DE</td>
        </tr>
        <tr>
          <td rowspan="12">公司或个人</td>
          <td>申请人</td>
          <td>pa</td>
          <td>是</td>
          <td>pa:国家电网公司</td>
        </tr>
        <tr>
          <td>申请人类型：企业、个人和其他、研究机构、大学</td>
          <td>ap-type</td>
          <td>否</td>
          <td>ap-type:企业</td>
        </tr>
        <tr>
          <td>当前专利权人</td>
          <td>patentee</td>
          <td>否</td>
          <td>patentee:华为技术有限公司</td>
        </tr>
        <tr>
          <td>发明（设计）人</td>
          <td>in</td>
          <td>是</td>
          <td>in:张伟</td>
        </tr>
        <tr>
          <td>代理人</td>
          <td>at</td>
          <td>否</td>
          <td>at:汤东凤</td>
        </tr>
        <tr>
          <td>代理机构</td>
          <td>ag</td>
          <td>否</td>
          <td>ag:\"中国专利代理(香港)有限公司\"</td>
        </tr>
        <tr>
          <td>转让人</td>
          <td>aor</td>
          <td>否</td>
          <td>aor:微软公司</td>
        </tr>
        <tr>
          <td>受让人</td>
          <td>aee</td>
          <td>否</td>
          <td>aee:美的集团股份有限公司</td>
        </tr>
        <tr>
          <td>许可人</td>
          <td>lor</td>
          <td>否</td>
          <td>lor:南京林业大学</td>
        </tr>
        <tr>
          <td>被许可人</td>
          <td>lee</td>
          <td>否</td>
          <td>lee:深圳市麦思美科技有限公司</td>
        </tr>
        <tr>
          <td>质权人</td>
          <td>pee</td>
          <td>是</td>
          <td>pee:青岛高创科技融资担保有限公司</td>
        </tr>
        <tr>
          <td>出质人</td>
          <td>por</td>
          <td>是</td>
          <td>por:神雾科技集团股份有限公司</td>
        </tr>
        <tr>
          <td rowspan="24">分类号</td>
          <td>IPC分类号</td>
          <td>ic</td>
          <td>是</td>
          <td>ic:B01D29/72</td>
        </tr>
        <tr>
          <td>IPC主分类号</td>
          <td>mc</td>
          <td>否</td>
          <td>mc:H04M1/02</td>
        </tr>
        <tr>
          <td>IPC主分类号部</td>
          <td>ipc-section</td>
          <td>是</td>
          <td>ipc-section:B</td>
        </tr>
        <tr>
          <td>IPC主分类号大类</td>
          <td>ipc-class</td>
          <td>是</td>
          <td>ipc-class:B27</td>
        </tr>
        <tr>
          <td>IPC主分类号小类</td>
          <td>ipc-subclass</td>
          <td>是</td>
          <td>ipc-subclass:B27K</td>
        </tr>
        <tr>
          <td>IPC主分类号大组</td>
          <td>ipc-group</td>
          <td>是</td>
          <td>ipc-group:B27K3</td>
        </tr>
        <tr>
          <td>IPC主分类号小组</td>
          <td>ipc-subgroup</td>
          <td>是</td>
          <td>ipc-subgroup:B27K352</td>
        </tr>
        <tr>
          <td>IPC分类号部</td>
          <td>ipc-section-list</td>
          <td>是</td>
          <td>ipc-section-list:B</td>
        </tr>
        <tr>
          <td>IPC分类号大类</td>
          <td>ipc-class-list</td>
          <td>是</td>
          <td>ipc-class-list:B27</td>
        </tr>
        <tr>
          <td>IPC分类号小类</td>
          <td>ipc-subclass-list</td>
          <td>是</td>
          <td>ipc-subclass-list:B27K</td>
        </tr>
        <tr>
          <td>IPC分类号大组</td>
          <td>ipc-group-list</td>
          <td>是</td>
          <td>ipc-group-list:B27K3</td>
        </tr>
        <tr>
          <td>IPC分类号小组</td>
          <td>ipc-subgroup-list</td>
          <td>是</td>
          <td>ipc-subgroup-list:B27K352</td>
        </tr>
        <tr>
          <td>CPC主分类部</td>
          <td>cpc-section</td>
          <td>是</td>
          <td>cpc-section:G</td>
        </tr>
        <tr>
          <td>CPC主分类大类</td>
          <td>cpc-class</td>
          <td>是</td>
          <td>cpc-class:G08</td>
        </tr>
        <tr>
          <td>CPC主分类小类</td>
          <td>cpc-subclass</td>
          <td>是</td>
          <td>cpc-subclass:G08C</td>
        </tr>
        <tr>
          <td>CPC主分类大组</td>
          <td>cpc-group</td>
          <td>是</td>
          <td>cpc-group:G08C19</td>
        </tr>
        <tr>
          <td>CPC主分类小组</td>
          <td>cpc-subgroup</td>
          <td>是</td>
          <td>cpc-subgroup:G08C1938</td>
        </tr>
        <tr>
          <td>CPC分类部</td>
          <td>cpc-section-list</td>
          <td>是</td>
          <td>cpc-section-list:G</td>
        </tr>
        <tr>
          <td>CPC分类大类</td>
          <td>cpc-class-list</td>
          <td>是</td>
          <td>cpc-class-list:G08</td>
        </tr>
        <tr>
          <td>CPC分类小类</td>
          <td>cpc-subclass-list</td>
          <td>是</td>
          <td>cpc-subclass-list:G08C</td>
        </tr>
        <tr>
          <td>CPC分类大组</td>
          <td>cpc-group-list</td>
          <td>是</td>
          <td>cpc-group-list:G08C19</td>
        </tr>
        <tr>
          <td>CPC分类小组</td>
          <td>cpc-subgroup-list</td>
          <td>是</td>
          <td>cpc-subgroup-list:G08C1938</td>
        </tr>
        <tr>
          <td>国民经济分类</td>
          <td>nation-class</td>
          <td>否</td>
          <td>nation-class:O</td>
        </tr>
        <tr>
          <td>国民经济分类门类</td>
          <td>nation-catclass</td>
          <td>否</td>
          <td>nation-catclass:8022</td>
        </tr>
        <tr>
          <td rowspan="10">时间</td>
          <td>申请日所在年</td>
          <td>ad-year</td>
          <td>否</td>
          <td>ad-year:2018</td>
        </tr>
        <tr>
          <td>申请日所在年月</td>
          <td>ad-month</td>
          <td>否</td>
          <td>ad-month:201803</td>
        </tr>
        <tr>
          <td>申请日</td>
          <td>ad</td>
          <td>否</td>
          <td>ad:20180302</td>
        </tr>
        <tr>
          <td>公开日所在年</td>
          <td>pd-year</td>
          <td>否</td>
          <td>pd-year:2018</td>
        </tr>
        <tr>
          <td>公开日所在年月</td>
          <td>pd-month</td>
          <td>否</td>
          <td>pd-month:201809</td>
        </tr>
        <tr>
          <td>公开日</td>
          <td>pd</td>
          <td>否</td>
          <td>pd:20180913</td>
        </tr>
        <tr>
          <td>转让年</td>
          <td>assignyear</td>
          <td>否</td>
          <td>assignyear:2019</td>
        </tr>
        <tr>
          <td>许可年</td>
          <td>licenseyear</td>
          <td>否</td>
          <td>licenseyear:2019</td>
        </tr>
        <tr>
          <td>质押年限</td>
          <td>pled-year</td>
          <td>是</td>
          <td>pled-year:2019</td>
        </tr>
        <tr>
          <td>维持年限：01 1年、02 2年、03 3年、04 5年、05 10年以内、06 其他</td>
          <td>valid-year</td>
          <td>是</td>
          <td>valid-year:01</td>
        </tr>
        <tr>
          <td rowspan="5">其它</td>
          <td>专利类型：01（发明申请），02（实用新型），03（外观设计）</td>
          <td>f-kind</td>
          <td>否</td>
          <td>f-kind:01</td>
        </tr>
        <tr>
          <td>专利类型：A，B，S，U</td>
          <td>kind</td>
          <td>否</td>
          <td>kind:B</td>
        </tr>
        <tr>
          <td>专利公开类型：发明申请、实用新型、发明授权</td>
          <td>pt</td>
          <td>否</td>
          <td>pt:C</td>
        </tr>
        <tr>
          <td>当前法律状态：01 在审 02 有效 03 无效 04 其它</td>
          <td>status-lite</td>
          <td>否</td>
          <td>status-lite:02</td>
        </tr>
        <tr>
          <td>质押类型：质押、保全</td>
          <td>pledge-type</td>
          <td>是</td>
          <td>pledge-type:质押</td>
        </tr>
        <tr>
          <td rowspan="11">专利基本信息（非统计维度）</td>
          <td>ROWKEY</td>
          <td>id</td>
          <td>否</td>
          <td>id:009517013102A</td>
        </tr>
        <tr>
          <td>专利名称</td>
          <td>ti</td>
          <td>否</td>
          <td>ti:\"计算机\"</td>
        </tr>
        <tr>
          <td>申请号</td>
          <td>an</td>
          <td>否</td>
          <td>an:200810111918.8</td>
        </tr>
        <tr>
          <td>申请国别-申请号</td>
          <td>anc-an</td>
          <td>否</td>
          <td>anc-an:CN200810111918.8</td>
        </tr>
        <tr>
          <td>公开号</td>
          <td>pn</td>
          <td>否</td>
          <td>pn:101587454</td>
        </tr>
        <tr>
          <td>公开国别-公开号</td>
          <td>pnc-pn</td>
          <td>否</td>
          <td>pnc-pn:CN101587454</td>
        </tr>
        <tr>
          <td>优先权号</td>
          <td>pr</td>
          <td>否</td>
          <td>pr:\"10/967,958\"</td>
        </tr>
        <tr>
          <td>摘要</td>
          <td>ab</td>
          <td>是</td>
          <td>ab:\"计算机\"</td>
        </tr>
        <tr>
          <td>权利要求</td>
          <td>cl</td>
          <td>是</td>
          <td>cl:\"计算机\"</td>
        </tr>
        <tr>
          <td>说明书-正文</td>
          <td>ds</td>
          <td>是</td>
          <td>ds:\"计算机\"</td>
        </tr>
        <tr>
          <td>申请人地址</td>
          <td>dz</td>
          <td>是</td>
          <td>dz:\"上海市浦东新区\"</td>
        </tr>
        <tr>
          <td rowspan="5">分词查询（非统计维度）</td>
          <td>专利标题，代理人，代理机构，申请人，发明人，摘要 组合查询索引</td>
          <td>all</td>
          <td>是</td>
          <td>all:\"计算机\"</td>
        </tr>
        <tr>
          <td>专利标题</td>
          <td>ti</td>
          <td>是</td>
          <td>ti:\"计算机\"</td>
        </tr>
        <tr>
          <td>代理人</td>
          <td>agentSearch</td>
          <td>是</td>
          <td>agentSearch:\"徐瑞丰\"</td>
        </tr>
        <tr>
          <td>代理机构</td>
          <td>agentOrgSearch</td>
          <td>是</td>
          <td>agentOrgSearch:\"专利商标事务所\"</td>
        </tr>
        <tr>
          <td>申请人</td>
          <td>applicantSearch</td>
          <td>是</td>
          <td>applicantSearch:\"三菱电机株式会社\"</td>
        </tr>
      </tbody>
    </table>
    <div class="title">常用查询参数</div>
    <table border="1" cellpadding="0" cellspacing="0" class="table2">
      <thead>
        <tr>
          <th>参数</th>
          <th>描述</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>：</td>
          <td>指定要查找的字段，比如：pnc:US，含义为专利公开国别为US的数据集</td>
        </tr>
        <tr>
          <td>？</td>
          <td>匹配单一字符，比如：ti:tes?匹配test/text</td>
        </tr>
        <tr>
          <td>*</td>
          <td>匹配0或多个字符，比如：ti:tes*匹配tes/testing/tester</td>
        </tr>
        <tr>
          <td>TO</td>
          <td>范围查询，{}不包含边界，[]包含边界，比如：ti:{A* TO C*}</td>
        </tr>
        <tr>
          <td>AND(&&)</td>
          <td>运算符两边的查询词同时出现 比如：ti:computer AND pnc:US</td>
        </tr>
        <tr>
          <td>OR</td>
          <td>运算符两边的查询词至少一个出现, 默认运算符，比如： ti:computer OR pnc:US</td>
        </tr>
        <tr>
          <td>NOT(!)</td>
          <td>运算符后面的查询词不出现，比如：ti:(* NOT 笔记本)</td>
        </tr>
        <tr>
          <td>[]</td>
          <td>包含范围边界</td>
        </tr>
        <tr>
          <td>{}</td>
          <td>不包含范围边界</td>
        </tr>
      </tbody>
    </table>
  </div>
</template>

<script>
  

  export default {
    data() {
      return {
        
      }
    },
    methods: {
      

    }
  }
</script>

<style scoped lang="less">
  #searchmore{
    width: 1170px;
    margin: 0 auto;
    .title{
      display: block;
      margin-top: 20px;
      margin-bottom: 16px;
      height: 20px;
      line-height: 20px;
      font-size: 20px;
      position: relative;
      color: #2f3030;
    }
    .table1,.table2{
      border: 1px solid rgba(239, 241, 242, 1);
      text-align: center;
      width: 100%;
      th{
        background: #eff3f5;
      }
      td,th{
        padding: 10px 6px;
        border: 1px solid #ddd;
      }
      tbody>tr:nth-child(2n+2){
        background: #F7F7F7;
      }
    }
    .table2{
      tr{
        td:last-child{
          text-align: start;
        }
      }
    }
  }
</style>