<template>
  <div id="searchmore">
    <div class="title">国家编码和名称对照表</div>
    <table border="1" cellpadding="0" cellspacing="0" class="table1">
      <thead>
        <tr>
          <th>国别编码</th>
          <th>国别名称</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>AD</td>
          <td>安道尔共和国</td>
        </tr>
        <tr>
          <td>AE</td>
          <td>阿拉伯联合酋长国</td>
        </tr>
        <tr>
          <td>AF</td>
          <td>阿富汗</td>
        </tr>
        <tr>
          <td>AG</td>
          <td>安提瓜和巴布达</td>
        </tr>
        <tr>
          <td>AI</td>
          <td>安圭拉岛</td>
        </tr>
        <tr>
          <td>AL</td>
          <td>阿尔巴尼亚</td>
        </tr>
        <tr>
          <td>AM</td>
          <td>亚美尼亚</td>
        </tr>
        <tr>
          <td>AO</td>
          <td>安哥拉</td>
        </tr>
        <tr>
          <td>AP</td>
          <td>非洲区域知识产权组织(ARIPO)</td>
        </tr>
        <tr>
          <td>AR</td>
          <td>阿根廷</td>
        </tr>
        <tr>
          <td>AT</td>
          <td>奥地利</td>
        </tr>
        <tr>
          <td>AU</td>
          <td>澳大利亚</td>
        </tr>
        <tr>
          <td>AW</td>
          <td>阿鲁巴</td>
        </tr>
        <tr>
          <td>AZ</td>
          <td>阿塞拜疆</td>
        </tr>
        <tr>
          <td>BA</td>
          <td>波斯尼亚和黑塞哥维那</td>
        </tr>
        <tr>
          <td>BB</td>
          <td>巴巴多斯</td>
        </tr>
        <tr>
          <td>BD</td>
          <td>孟加拉国</td>
        </tr>
        <tr>
          <td>BE</td>
          <td>比利时</td>
        </tr>
        <tr>
          <td>BF</td>
          <td>布基纳法索</td>
        </tr>
        <tr>
          <td>BG</td>
          <td>保加利亚</td>
        </tr>
        <tr>
          <td>BH</td>
          <td>巴林</td>
        </tr>
        <tr>
          <td>BI</td>
          <td>布隆迪</td>
        </tr>
        <tr>
          <td>BJ</td>
          <td>贝宁</td>
        </tr>
        <tr>
          <td>BM</td>
          <td>百慕大群岛</td>
        </tr>
        <tr>
          <td>BN</td>
          <td>文莱</td>
        </tr>
        <tr>
          <td>BO</td>
          <td>玻利维亚</td>
        </tr>
        <tr>
          <td>BQ</td>
          <td>博内尔岛，圣尤斯特歇斯岛和萨巴</td>
        </tr>
        <tr>
          <td>BR</td>
          <td>巴西</td>
        </tr>
        <tr>
          <td>BS</td>
          <td>巴哈马</td>
        </tr>
        <tr>
          <td>BT</td>
          <td>不丹</td>
        </tr>
        <tr>
          <td>BV</td>
          <td>布韦岛</td>
        </tr>
        <tr>
          <td>BW</td>
          <td>博茨瓦纳</td>
        </tr>
        <tr>
          <td>BX</td>
          <td>比荷卢知识产权办公室(BOIP)</td>
        </tr>
        <tr>
          <td>BY</td>
          <td>白俄罗斯</td>
        </tr>
        <tr>
          <td>BZ</td>
          <td>伯利兹</td>
        </tr>
        <tr>
          <td>CA</td>
          <td>加拿大</td>
        </tr>
        <tr>
          <td>CD</td>
          <td>刚果民主共和国</td>
        </tr>
        <tr>
          <td>CF</td>
          <td>中非共和国</td>
        </tr>
        <tr>
          <td>CG</td>
          <td>刚果(布)</td>
        </tr>
        <tr>
          <td>CH</td>
          <td>瑞士</td>
        </tr>
        <tr>
          <td>CI</td>
          <td>科特迪瓦</td>
        </tr>
        <tr>
          <td>CK</td>
          <td>库克群岛</td>
        </tr>
        <tr>
          <td>CL</td>
          <td>智利</td>
        </tr>
        <tr>
          <td>CM</td>
          <td>喀麦隆</td>
        </tr>
        <tr>
          <td>CN</td>
          <td>中国</td>
        </tr>
        <tr>
          <td>CO</td>
          <td>哥伦比亚</td>
        </tr>
        <tr>
          <td>CR</td>
          <td>哥斯达黎加</td>
        </tr>
        <tr>
          <td>CU</td>
          <td>古巴</td>
        </tr>
        <tr>
          <td>CV</td>
          <td>佛得角</td>
        </tr>
        <tr>
          <td>CW</td>
          <td>库拉索</td>
        </tr>
        <tr>
          <td>CY</td>
          <td>塞浦路斯</td>
        </tr>
        <tr>
          <td>CZ</td>
          <td>捷克</td>
        </tr>
        <tr>
          <td>DE</td>
          <td>德国</td>
        </tr>
        <tr>
          <td>DJ</td>
          <td>吉布提</td>
        </tr>
        <tr>
          <td>DK</td>
          <td>丹麦</td>
        </tr>
        <tr>
          <td>DM</td>
          <td>多米尼克</td>
        </tr>
        <tr>
          <td>DO</td>
          <td>多明尼加共和国</td>
        </tr>
        <tr>
          <td>DZ</td>
          <td>阿尔及利亚</td>
        </tr>
        <tr>
          <td>EA</td>
          <td>欧亚专利组织(EAPO)</td>
        </tr>
        <tr>
          <td>EC</td>
          <td>厄瓜多尔</td>
        </tr>
        <tr>
          <td>EE</td>
          <td>爱沙尼亚</td>
        </tr>
        <tr>
          <td>EG</td>
          <td>埃及</td>
        </tr>
        <tr>
          <td>EH</td>
          <td>西撒哈拉</td>
        </tr>
        <tr>
          <td>EM</td>
          <td>内部市场协调局(商标和外观设计)(OHIM)</td>
        </tr>
        <tr>
          <td>EP</td>
          <td>欧洲专利局(EPO)</td>
        </tr>
        <tr>
          <td>ER</td>
          <td>厄立特里亚</td>
        </tr>
        <tr>
          <td>ES</td>
          <td>西班牙</td>
        </tr>
        <tr>
          <td>ET</td>
          <td>埃塞俄比亚</td>
        </tr>
        <tr>
          <td>FI</td>
          <td>芬兰</td>
        </tr>
        <tr>
          <td>FJ</td>
          <td>斐济群岛</td>
        </tr>
        <tr>
          <td>FK</td>
          <td>马尔维纳斯群岛(福克兰)</td>
        </tr>
        <tr>
          <td>FO</td>
          <td>法罗群岛</td>
        </tr>
        <tr>
          <td>FR</td>
          <td>法国</td>
        </tr>
        <tr>
          <td>GA</td>
          <td>加蓬</td>
        </tr>
        <tr>
          <td>GB</td>
          <td>英国</td>
        </tr>
        <tr>
          <td>GC</td>
          <td>海湾阿拉伯国家合作委员会专利局</td>
        </tr>
        <tr>
          <td>GD</td>
          <td>格林纳达</td>
        </tr>
        <tr>
          <td>GE</td>
          <td>格鲁吉亚</td>
        </tr>
        <tr>
          <td>GG</td>
          <td>根西岛</td>
        </tr>
        <tr>
          <td>GH</td>
          <td>加纳</td>
        </tr>
        <tr>
          <td>GI</td>
          <td>直布罗陀</td>
        </tr>
        <tr>
          <td>GL</td>
          <td>格陵兰</td>
        </tr>
        <tr>
          <td>GM</td>
          <td>冈比亚</td>
        </tr>
        <tr>
          <td>GN</td>
          <td>几内亚</td>
        </tr>
        <tr>
          <td>GQ</td>
          <td>赤道几内亚</td>
        </tr>
        <tr>
          <td>GR</td>
          <td>希腊</td>
        </tr>
        <tr>
          <td>GS</td>
          <td>南乔治亚岛和南桑威奇群岛</td>
        </tr>
        <tr>
          <td>GT</td>
          <td>危地马拉</td>
        </tr>
        <tr>
          <td>GW</td>
          <td>几内亚比绍</td>
        </tr>
        <tr>
          <td>GY</td>
          <td>圭亚那</td>
        </tr>
        <tr>
          <td>HK</td>
          <td>中国香港</td>
        </tr>
        <tr>
          <td>HN</td>
          <td>洪都拉斯</td>
        </tr>
        <tr>
          <td>HR</td>
          <td>克罗地亚</td>
        </tr>
        <tr>
          <td>HT</td>
          <td>海地</td>
        </tr>
        <tr>
          <td>HU</td>
          <td>匈牙利</td>
        </tr>
        <tr>
          <td>IB</td>
          <td>世界知识产权组织(WIPO)</td>
        </tr>
        <tr>
          <td>ID</td>
          <td>印尼</td>
        </tr>
        <tr>
          <td>IE</td>
          <td>爱尔兰</td>
        </tr>
        <tr>
          <td>IL</td>
          <td>以色列</td>
        </tr>
        <tr>
          <td>IM</td>
          <td>马恩岛</td>
        </tr>
        <tr>
          <td>IN</td>
          <td>印度</td>
        </tr>
        <tr>
          <td>IQ</td>
          <td>伊拉克</td>
        </tr>
        <tr>
          <td>IR</td>
          <td>伊朗</td>
        </tr>
        <tr>
          <td>IS</td>
          <td>冰岛</td>
        </tr>
        <tr>
          <td>IT</td>
          <td>意大利</td>
        </tr>
        <tr>
          <td>JE</td>
          <td>泽西岛</td>
        </tr>
        <tr>
          <td>JM</td>
          <td>牙买加</td>
        </tr>
        <tr>
          <td>JO</td>
          <td>约旦</td>
        </tr>
        <tr>
          <td>JP</td>
          <td>日本</td>
        </tr>
        <tr>
          <td>KE</td>
          <td>肯尼亚</td>
        </tr>
        <tr>
          <td>KG</td>
          <td>吉尔吉斯斯坦</td>
        </tr>
        <tr>
          <td>KH</td>
          <td>柬埔寨</td>
        </tr>
        <tr>
          <td>KI</td>
          <td>基里巴斯</td>
        </tr>
        <tr>
          <td>KM</td>
          <td>基里巴斯</td>
        </tr>
        <tr>
          <td>KN</td>
          <td>圣基茨和尼维斯</td>
        </tr>
        <tr>
          <td>KP</td>
          <td>朝鲜</td>
        </tr>
        <tr>
          <td>KR</td>
          <td>韩国</td>
        </tr>
        <tr>
          <td>KW</td>
          <td>科威特</td>
        </tr>
        <tr>
          <td>KY</td>
          <td>开曼群岛</td>
        </tr>
        <tr>
          <td>KZ</td>
          <td>哈萨克斯坦</td>
        </tr>
        <tr>
          <td>LA</td>
          <td>老挝</td>
        </tr>
        <tr>
          <td>LB</td>
          <td>黎巴嫩</td>
        </tr>
        <tr>
          <td>LC</td>
          <td>圣卢西亚</td>
        </tr>
        <tr>
          <td>LI</td>
          <td>列支敦士登</td>
        </tr>
        <tr>
          <td>LK</td>
          <td>斯里兰卡</td>
        </tr>
        <tr>
          <td>LR</td>
          <td>利比里亚</td>
        </tr>
        <tr>
          <td>LS</td>
          <td>莱索托</td>
        </tr>
        <tr>
          <td>LT</td>
          <td>立陶宛</td>
        </tr>
        <tr>
          <td>LU</td>
          <td>卢森堡</td>
        </tr>
        <tr>
          <td>LV</td>
          <td>拉脱维亚</td>
        </tr>
        <tr>
          <td>LY</td>
          <td>利比亚</td>
        </tr>
        <tr>
          <td>MA</td>
          <td>摩洛哥</td>
        </tr>
        <tr>
          <td>MC</td>
          <td>摩纳哥</td>
        </tr>
        <tr>
          <td>MD</td>
          <td>摩尔多瓦</td>
        </tr>
        <tr>
          <td>ME</td>
          <td>黑山</td>
        </tr>
        <tr>
          <td>MG</td>
          <td>马达加斯加</td>
        </tr>
        <tr>
          <td>MK</td>
          <td>马其顿</td>
        </tr>
        <tr>
          <td>ML</td>
          <td>马里</td>
        </tr>
        <tr>
          <td>MM</td>
          <td>缅甸</td>
        </tr>
        <tr>
          <td>MN</td>
          <td>蒙古国；蒙古</td>
        </tr>
        <tr>
          <td>MO</td>
          <td>中国澳门</td>
        </tr>
        <tr>
          <td>MP</td>
          <td>北马里亚纳群岛</td>
        </tr>
        <tr>
          <td>MR</td>
          <td>毛里塔尼亚</td>
        </tr>
        <tr>
          <td>MS</td>
          <td>蒙塞拉特岛</td>
        </tr>
        <tr>
          <td>MT</td>
          <td>马耳他</td>
        </tr>
        <tr>
          <td>MU</td>
          <td>毛里求斯</td>
        </tr>
        <tr>
          <td>MV</td>
          <td>马尔代夫</td>
        </tr>
        <tr>
          <td>MW</td>
          <td>马拉维</td>
        </tr>
        <tr>
          <td>MX</td>
          <td>墨西哥</td>
        </tr>
        <tr>
          <td>MY</td>
          <td>马来西亚</td>
        </tr>
        <tr>
          <td>MZ</td>
          <td>莫桑比克</td>
        </tr>
        <tr>
          <td>NA</td>
          <td>纳米比亚</td>
        </tr>
        <tr>
          <td>NE</td>
          <td>尼日尔</td>
        </tr>
        <tr>
          <td>NG</td>
          <td>尼日利亚</td>
        </tr>
        <tr>
          <td>NI</td>
          <td>尼加拉瓜</td>
        </tr>
        <tr>
          <td>NL</td>
          <td>荷兰</td>
        </tr>
        <tr>
          <td>NO</td>
          <td>挪威</td>
        </tr>
        <tr>
          <td>NP</td>
          <td>尼泊尔</td>
        </tr>
        <tr>
          <td>NR</td>
          <td>瑙鲁</td>
        </tr>
        <tr>
          <td>NZ</td>
          <td>新西兰</td>
        </tr>
        <tr>
          <td>OA</td>
          <td>非洲知识产权组织(OAPI)</td>
        </tr>
        <tr>
          <td>OM</td>
          <td>阿曼</td>
        </tr>
        <tr>
          <td>PA</td>
          <td>巴拿马</td>
        </tr>
        <tr>
          <td>PE</td>
          <td>秘鲁</td>
        </tr>
        <tr>
          <td>PG</td>
          <td>巴布亚新几内亚</td>
        </tr>
        <tr>
          <td>PH</td>
          <td>菲律宾</td>
        </tr>
        <tr>
          <td>PK</td>
          <td>巴基斯坦</td>
        </tr>
        <tr>
          <td>PL</td>
          <td>波兰</td>
        </tr>
        <tr>
          <td>PT</td>
          <td>葡萄牙</td>
        </tr>
        <tr>
          <td>PW</td>
          <td>帕劳</td>
        </tr>
        <tr>
          <td>PY</td>
          <td>巴拉圭</td>
        </tr>
        <tr>
          <td>QA</td>
          <td>卡塔尔</td>
        </tr>
        <tr>
          <td>QZ</td>
          <td>欧洲共同体之植物多样性总署(CPVO)</td>
        </tr>
        <tr>
          <td>RO</td>
          <td>罗马尼亚</td>
        </tr>
        <tr>
          <td>RS</td>
          <td>塞尔维亚</td>
        </tr>
        <tr>
          <td>RU</td>
          <td>俄罗斯</td>
        </tr>
        <tr>
          <td>RW</td>
          <td>卢旺达</td>
        </tr>
        <tr>
          <td>SA</td>
          <td>沙特阿拉伯</td>
        </tr>
        <tr>
          <td>SB</td>
          <td>所罗门群岛</td>
        </tr>
        <tr>
          <td>SC</td>
          <td>塞舌尔</td>
        </tr>
        <tr>
          <td>SD</td>
          <td>苏丹</td>
        </tr>
        <tr>
          <td>SE</td>
          <td>瑞典</td>
        </tr>
        <tr>
          <td>SG</td>
          <td>新加坡</td>
        </tr>
        <tr>
          <td>SH</td>
          <td>圣赫勒拿</td>
        </tr>
        <tr>
          <td>SI</td>
          <td>斯洛文尼亚</td>
        </tr>
        <tr>
          <td>SK</td>
          <td>斯洛伐克</td>
        </tr>
        <tr>
          <td>SL</td>
          <td>塞拉利昂</td>
        </tr>
        <tr>
          <td>SM</td>
          <td>圣马力诺</td>
        </tr>
        <tr>
          <td>SN</td>
          <td>塞内加尔</td>
        </tr>
        <tr>
          <td>SO</td>
          <td>索马里</td>
        </tr>
        <tr>
          <td>SR</td>
          <td>苏里南</td>
        </tr>
        <tr>
          <td>ST</td>
          <td>圣多美和普林西比</td>
        </tr>
        <tr>
          <td>SV</td>
          <td>萨尔瓦多</td>
        </tr>
        <tr>
          <td>SX</td>
          <td>荷属圣马丁</td>
        </tr>
        <tr>
          <td>SY</td>
          <td>叙利亚</td>
        </tr>
        <tr>
          <td>SZ</td>
          <td>斯威士兰</td>
        </tr>
        <tr>
          <td>TC</td>
          <td>特克斯和凯科斯群岛</td>
        </tr>
        <tr>
          <td>TD</td>
          <td>乍得</td>
        </tr>
        <tr>
          <td>TG</td>
          <td>多哥</td>
        </tr>
        <tr>
          <td>TH</td>
          <td>泰国</td>
        </tr>
        <tr>
          <td>TJ</td>
          <td>塔吉克斯坦</td>
        </tr>
        <tr>
          <td>TL</td>
          <td>东帝汶</td>
        </tr>
        <tr>
          <td>TM</td>
          <td>土库曼斯坦</td>
        </tr>
        <tr>
          <td>TN</td>
          <td>突尼斯</td>
        </tr>
        <tr>
          <td>TO</td>
          <td>汤加</td>
        </tr>
        <tr>
          <td>TR</td>
          <td>土耳其</td>
        </tr>
        <tr>
          <td>TT</td>
          <td>特立尼达和多巴哥</td>
        </tr>
        <tr>
          <td>TV</td>
          <td>图瓦卢</td>
        </tr>
        <tr>
          <td>TW</td>
          <td>中国台湾</td>
        </tr>
        <tr>
          <td>TZ</td>
          <td>坦桑尼亚</td>
        </tr>
        <tr>
          <td>UA</td>
          <td>乌克兰</td>
        </tr>
        <tr>
          <td>UG</td>
          <td>乌干达</td>
        </tr>
        <tr>
          <td>US</td>
          <td>美国</td>
        </tr>
        <tr>
          <td>UY</td>
          <td>乌拉圭</td>
        </tr>
        <tr>
          <td>UZ</td>
          <td>乌兹别克斯坦</td>
        </tr>
        <tr>
          <td>VA</td>
          <td>梵蒂冈</td>
        </tr>
        <tr>
          <td>VC</td>
          <td>圣文森特和格林纳丁斯</td>
        </tr>
        <tr>
          <td>VE</td>
          <td>委内瑞拉</td>
        </tr>
        <tr>
          <td>VG</td>
          <td>英属维尔京群岛</td>
        </tr>
        <tr>
          <td>VN</td>
          <td>越南</td>
        </tr>
        <tr>
          <td>VU</td>
          <td>瓦努阿图</td>
        </tr>
        <tr>
          <td>WO</td>
          <td>世界知识产权组织</td>
        </tr>
        <tr>
          <td>WS</td>
          <td>萨摩亚</td>
        </tr>
        <tr>
          <td>XN</td>
          <td>北欧专利研究所(NPI)</td>
        </tr>
        <tr>
          <td>YE</td>
          <td>也门</td>
        </tr>
        <tr>
          <td>ZA</td>
          <td>南非</td>
        </tr>
        <tr>
          <td>ZM</td>
          <td>赞比亚</td>
        </tr>
        <tr>
          <td>ZW</td>
          <td>津巴布韦</td>
        </tr>
        <tr>
          <td>CS</td>
          <td>捷克斯拉夫</td>
        </tr>
        <tr>
          <td>SU</td>
          <td>苏联</td>
        </tr>
        <tr>
          <td>YU</td>
          <td>南斯拉夫</td>
        </tr>
        <tr>
          <td>DD</td>
          <td>东德</td>
        </tr>
      </tbody>
    </table>
  </div>
</template>

<script>
  

  export default {
    data() {
      return {
        
      }
    },
    methods: {
      

    }
  }
</script>

<style scoped lang="less">
  #searchmore{
    width: 1170px;
    margin: 0 auto;
    .title{
      display: block;
      margin-top: 20px;
      margin-bottom: 16px;
      height: 20px;
      line-height: 20px;
      font-size: 20px;
      position: relative;
      color: #2f3030;
    }
    .table1,.table2{
      border: 1px solid rgba(239, 241, 242, 1);
      width: 100%;
      th{
        background: #eff3f5;
      }
      td,th{
        padding: 10px 6px;
        border: 1px solid #ddd;
      }
      tbody>tr:nth-child(2n+2){
        background: #F7F7F7;
      }
    }
    .table2{
      tr{
        td:last-child{
          text-align: start;
        }
      }
    }
  }
</style>